apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: com--
build:
  artifacts:
    - image: martin590/com-project1
      context: quiz-platform/api-gateway
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: quiz-platform
        chartPath: quiz-platform/quiz-chart
        valuesFiles:
          - quiz-platform/quiz-chart/values.yaml
        version: 0.1.0
