global:
  imagePullPolicy: Never

# fake values
db:
  userServicePassword: "changeme"
  quizServicePassword: "changeme"
  resultServicePassword: "changeme"
  jwtSecret: "changeme"

apiGateway:
  name: api-gateway
  image: martin590/com-project1:api-gateway
  replicas: 1
  port: 8080
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"

userService:
  name: user-service
  image: martin590/com-project1:user-service
  replicas: 1
  port: 5000
  envSecret: db-urls
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"

quizService:
  name: quiz-service
  image: martin590/com-project1:quiz-service
  replicas: 1
  port: 5001
  envSecret: db-urls

resultService:
  name: result-service
  image: martin590/com-project1:result-service
  replicas: 1
  port: 5002
  envSecret: db-urls
  env:
    QUIZ_SERVICE_URL: "http://quiz-service:5001"