{{- range $key, $service := .Values }}
{{- if (hasKey $service "name") }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $service.name }}
spec:
  replicas: {{ $service.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ $service.name }}
  template:
    metadata:
      labels:
        app: {{ $service.name }}
    spec:
      containers:
        - name: {{ $service.name }}
          image: {{ $service.image }}
          imagePullPolicy: {{ $.Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ $service.port }}
          {{- if $service.envSecret }}
          envFrom:
            - secretRef:
                name: {{ $service.envSecret }}
          {{- end }}
          {{- if $service.env }}
          env:
            {{- range $name, $value := $service.env }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          {{- if $service.resources }}
          resources:
            {{- toYaml $service.resources | nindent 12 }}
          {{- end }}
{{- end }}
{{- end }}