server {
    listen 8000;

    location /users {
        proxy_pass http://user-service:5000;
    }

    location /quizzes {
        proxy_pass http://quiz-service:5001;
    }

    location /results {
        proxy_pass http://result-service:5002;
    }

    location / {
        return 200 '{"message":"api gateway working"}';
        add_header Content-Type application/json;
    }
}