server {
    listen 8000;

    location /api/users {
        proxy_pass http://user-service:5000;
    }

    location /api/quizzes {
        proxy_pass http://quiz-service:5001;
    }

    location /api/results {
        proxy_pass http://result-service:5002;
    }

    location / {
        return 200 '{"message":"api gateway working"}';
        add_header Content-Type application/json;
    }
}
